### ISSUE TITLE
Language of the book

### ISSUE THREAD

**Issue by hemmond** [psztrnk/catalog#6]
It would be good to add a column "language" to table "books"

For example I am from Czech Republic, I have some books in Czech, some in Slovak (language very close to Czech - we are neighbours), some in English, and sometimes I have the same book in English and in Czech. It would be great if I could keep the information in the database about in which language the book is. 

Maybe it would be good to add also column "original title" through which the books in different languages (and with different ISBNs) can connect through.

**Comment by psztrnk** [comment]
This is a good one. I'll definitely implement this to Catalog2, but also to Catalog if I'll have time.

**Comment by psztrnk** [comment]
Implemented in v1.1
