### ISSUE TITLE
Series

### ISSUE THREAD

**Issue by hemmond** [psztrnk/catalog#7]
Some of the books I have are part of a series (for example Isaac Asimov's Foundation series, or Terry Pratchett' Discworld series). It would be useful if there are columns in the database for "series name" and for number of the book in the series (for example "Guards! Guards!" are part of "Discworld" series and it's 8th book in the series. 

Sometimes book is part of the series, but has no number (for example "The Streets of Ankh-Morpork"). In that case, NULL (or 0) value should be acceptable.

**Comment by psztrnk** [comment]
I see your point and will implement this if I find the time (also for Catalog2).

Currently I am including this info to the title, eg. "Guards! Guards! (Discworld 8.)" or "Discworld: Guards! Guards! (8)" or something similar. So when I search for "title: Discworld", all the books'd pop up in the results. I admit that this isn't the most sophisticated approach, but works well and doesn't require a system that is more complex than my needs were.

**Comment by hemmond** [comment]
That is what I basically did for the time being. Except I used square brackets (less likely to show up in book Title). 

Thank you for replies and for considering. :)

**Comment by psztrnk** [comment]
Implemented in v1.1
